# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bfgs_optim <- function(params_no_na, SEM_likelihood, data, exact_value, control) {
    .Call(`_bdsm_bfgs_optim`, params_no_na, SEM_likelihood, data, exact_value, control)
}

